### ISSUE TITLE
Link to EGI IGTF in Quick Start is broken

### ISSUE THREAD

**Issue by maxnoe** [cern-fts/fts3#10]
The link on this page here: https://fts3-docs.web.cern.ch/fts3-docs/docs/install/quick.html that is supposed to link to the EGI IGTF release procedure now redirects to the landing page of a confluence, from which it is not obvious how to access the page that was intended to be linked.

**Comment by mpatrascoiu** [comment]
Hello,

Thank you for raising this issue!

I've updated the documentation. Now we explicitly list the contents of the required `/etc/yum.repos.d/EGI-trustanchors.repo` file.

Cheers,
Mihai
